- name: "Create proxy_net if it does not exist"
  become: True
  tags:
    - transmission_deploy
    - transmission_setup
  docker_network:
    name: proxy_net

- name: "Start transmission container w/ ssl"
  when: SSL == True
  become: True
  tags:
    - transmission_deploy
    - transmission_update
    - transmission_restore
  docker_container:
    name: transmission
    restart_policy: always
    image: linuxserver/transmission
    pull: True
    state: started
    env:
     VIRTUAL_HOST: "{{ transmission_domain_name }}"
     VIRTUAL_PROTO: http
     VIRTUAL_PORT: 8081
     LETSENCRYPT_HOST: "{{ transmission_letsencrypt_domain_name }}"
     LETSENCRYPT_EMAIL: "{{ transmission_letsencrypt_mail }}"
     LETSENCRYPT_TEST: "{{ transmission_letsencrypt_testmode }}"

    networks:
      - name: proxy_net
    volumes:
      - "{{ transmission_downloads_files }}:/downloads"
      - "{{conf_volume}}:/config"

- name: "Start transmission container w/o SSL"
  become: True
  when: SSL == False
  tags:
    - transmission_update
    - transmission_deploy
    - transmission_restore
  docker_container:
    name: transmission
    image: linuxserver/transmission
    pull: True
    restart_policy: always
    state: started
    env:
     VIRTUAL_HOST: "{{ transmission_domain_name }}"
     VIRTUAL_PROTO: http
     VIRTUAL_PORT: 8081
    networks:
      - name: proxy_net
    volumes:
      - "{{ transmission_downloads_files }}:/downloads"
      - "{{conf_volume}}:/config"
